services:
  postgres:
    build:
      context: ./database
      dockerfile: Database.Dockerfile
    container_name: chicken-nuggets-postgres
    environment:
      POSTGRES_DB: chicken_nuggets_insurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: